services:

  cftunnel:
    image: cloudflare/cloudflared:2024.4.1
    # container_name: cloudflare-tunnel
    # hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
